site :opscode

#base
cookbook 'apt', '1.9.2'
cookbook 'build-essential', '1.4.0'
cookbook 'ruby'
cookbook 'git'
cookbook 'curl'

cookbook 'apache2'
cookbook 'openssl'
cookbook 'erlang'
cookbook 'selinux'
cookbook 'yum'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'database'
cookbook 'postgresql'
cookbook 'aws'
cookbook 'xfs'
cookbook 'rabbitmq'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'runit'
cookbook 'rsyslog', git:'https://github.com/opscode-cookbooks/rsyslog'

#openstack

cookbook 'nova', git:'https://github.com/rcbops-cookbooks/nova.git', branch:'grizzly'
cookbook 'keystone', git:'https://github.com/rcbops-cookbooks/keystone.git', branch:'grizzly'
cookbook 'glance', git:'https://github.com/rcbops-cookbooks/glance.git', branch:'grizzly'
cookbook 'horizon', git:'https://github.com/rcbops-cookbooks/horizon.git', branch:'grizzly'
cookbook 'swift', git:'https://github.com/rcbops-cookbooks/swift.git', branch:'grizzly'
cookbook 'osops-utils', git:'https://github.com/rcbops-cookbooks/osops-utils.git', branch:'grizzly'
cookbook 'dsh', git:'https://github.com/rcbops-cookbooks/dsh.git', branch:'grizzly'
cookbook 'exerstack', git:'https://github.com/rcbops-cookbooks/exerstack.git', branch:'grizzly'
cookbook 'kong', git:'https://github.com/rcbops-cookbooks/kong.git', branch:'grizzly'
cookbook 'collectd', git:'https://github.com/rcbops-cookbooks/collectd.git', branch:'grizzly'
cookbook 'collectd-plugins', git:'https://github.com/rcbops-cookbooks/collectd-plugins.git', branch:'grizzly'
cookbook 'monit', git:'https://github.com/rcbops-cookbooks/monit.git', branch:'grizzly'
cookbook 'graphite', git:'https://github.com/rcbops-cookbooks/graphite.git', branch:'grizzly'
cookbook 'collectd-graphite', git:'https://github.com/rcbops-cookbooks/collectd-graphite.git', branch:'grizzly'
cookbook 'modules', git:'https://github.com/rcbops-cookbooks/modules.git', branch:'grizzly'
cookbook 'sysctl', git:'https://github.com/rcbops-cookbooks/sysctl.git', branch:'grizzly'
cookbook 'hardware', git:'https://github.com/rcbops-cookbooks/hardware', branch:'grizzly'
cookbook 'monitoring', git:'https://github.com/rcbops-cookbooks/monitoring.git', branch:'grizzly'
cookbook 'sosreport', git:'https://github.com/rcbops-cookbooks/sosreport.git', branch:'grizzly'
cookbook 'rabbitmq-openstack', git:'https://github.com/rcbops-cookbooks/rabbitmq-openstack.git', branch:'grizzly'
cookbook 'mysql-openstack', git:'https://github.com/rcbops-cookbooks/mysql-openstack.git', branch:'grizzly'
cookbook 'cinder', git:'https://github.com/rcbops-cookbooks/cinder.git', branch:'grizzly'
cookbook 'haproxy', git:'https://github.com/rcbops-cookbooks/haproxy.git', branch:'grizzly'
cookbook 'nova-network', git:'https://github.com/rcbops-cookbooks/nova-network.git', branch:'grizzly'
cookbook 'keepalived', git:'https://github.com/rcbops-cookbooks/keepalived.git', branch:'grizzly'
cookbook 'openstack-ha', git:'https://github.com/rcbops-cookbooks/openstack-ha.git', branch:'grizzly'
cookbook 'tempest', git:'https://github.com/rcbops-cookbooks/tempest.git', branch:'grizzly'
cookbook 'openstack-logging', git:'https://github.com/rcbops-cookbooks/openstack-logging.git', branch:'grizzly'
cookbook 'ceilometer', git:'https://github.com/rcbops-cookbooks/ceilometer.git', branch:'grizzly'
cookbook 'openstack-monitoring', git:'https://github.com/rcbops-cookbooks/openstack-monitoring.git', branch:'grizzly'
cookbook 'memcached-openstack', git:'https://github.com/rcbops-cookbooks/memcached-openstack.git', branch:'grizzly'

#cookbook 'nova', git: 'https://github.com/rcbops-cookbooks/nova.git', branch:'grizzly'
#cookbook 'keystone', git: 'https://github.com/rcbops-cookbooks/keystone.git', branch:'grizzly'
#cookbook 'glance', git: 'https://github.com/rcbops-cookbooks/glance.git', branch:'grizzly'
#cookbook 'horizon', git: 'https://github.com/rcbops-cookbooks/horizon.git', branch:'grizzly'
#cookbook 'swift', git: 'https://github.com/rcbops-cookbooks/swift.git', branch:'grizzly'
#cookbook 'osops-utils', git: 'https://github.com/rcbops-cookbooks/osops-utils.git', branch:'grizzly'
#cookbook 'dsh', git: 'https://github.com/rcbops-cookbooks/dsh.git', branch:'grizzly'
#cookbook 'exerstack', git: 'https://github.com/rcbops-cookbooks/exerstack.git', branch:'grizzly'
#cookbook 'kong', git: 'https://github.com/rcbops-cookbooks/kong.git', branch:'grizzly'
#cookbook 'collectd', git: 'https://github.com/rcbops-cookbooks/collectd.git', branch:'grizzly'
#cookbook 'collectd-plugins', git: 'https://github.com/rcbops-cookbooks/collectd-plugins.git', branch:'grizzly'
#cookbook 'monit', git: 'https://github.com/rcbops-cookbooks/monit.git', branch:'grizzly'
#cookbook 'graphite', git: 'https://github.com/rcbops-cookbooks/graphite.git', branch:'grizzly'
#cookbook 'collectd-graphite', git: 'https://github.com/rcbops-cookbooks/collectd-graphite.git', branch:'grizzly'
#cookbook 'rsyslog', git: 'https://github.com/rcbops-cookbooks/rsyslog.git', branch:'grizzly'
#cookbook 'modules', git: 'https://github.com/rcbops-cookbooks/modules.git', branch:'grizzly'
#cookbook 'sysctl', git: 'https://github.com/rcbops-cookbooks/sysctl.git', branch:'grizzly'
#cookbook 'hardware', git: 'https://github.com/rcbops-cookbooks/hardware', branch:'grizzly'
#cookbook 'monitoring', git: 'https://github.com/rcbops-cookbooks/monitoring.git', branch:'grizzly'
#cookbook 'sosreport', git: 'https://github.com/rcbops-cookbooks/sosreport.git', branch:'grizzly'
#cookbook 'rabbitmq-openstack', git: 'https://github.com/rcbops-cookbooks/rabbitmq-openstack.git', branch:'grizzly'
#cookbook 'mysql-openstack', git: 'https://github.com/rcbops-cookbooks/mysql-openstack.git', branch:'grizzly'
#cookbook 'cinder', git: 'https://github.com/rcbops-cookbooks/cinder.git', branch:'grizzly'
#cookbook 'haproxy', git: 'https://github.com/rcbops-cookbooks/haproxy.git', branch:'grizzly'
#cookbook 'corosync', git: 'https://github.com/rcbops-cookbooks/corosync.git'
#cookbook 'nova-network', git: 'https://github.com/rcbops-cookbooks/nova-network.git', branch:'grizzly'
#cookbook 'keepalived', git: 'https://github.com/rcbops-cookbooks/keepalived.git', branch:'grizzly'
#cookbook 'openstack-ha', git: 'https://github.com/rcbops-cookbooks/openstack-ha.git', branch:'grizzly'
#cookbook 'memcached-openstack', git: 'https://github.com/rcbops-cookbooks/memcached-openstack.git', branch:'grizzly'
