site :opscode

#base
cookbook 'apt', '1.9.2'
cookbook 'build-essential', '1.4.0'
cookbook 'ruby'
cookbook 'git'
cookbook 'curl'

#openstack
cookbook 'apache2'
cookbook 'openssl'
cookbook 'erlang'
cookbook 'selinux'
cookbook 'yum'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'memcached'
cookbook 'runit'
cookbook 'aws'
cookbook 'xfs'
cookbook 'rabbitmq'
cookbook 'mysql'

cookbook 'nova', git: 'https://github.com/rcbops-cookbooks/nova.git', branch:'folsom'
cookbook 'keystone', git: 'https://github.com/rcbops-cookbooks/keystone.git', branch:'folsom'
cookbook 'glance', git: 'https://github.com/rcbops-cookbooks/glance.git', branch:'folsom'
cookbook 'horizon', git: 'https://github.com/rcbops-cookbooks/horizon.git', branch:'folsom'
cookbook 'database', git: 'https://github.com/opscode-cookbooks/database.git'
cookbook 'postgresql', git: 'https://github.com/opscode-cookbooks/postgresql.git'
cookbook 'swift', git: 'https://github.com/rcbops-cookbooks/swift.git', branch:'folsom'
cookbook 'osops-utils', git: 'https://github.com/rcbops-cookbooks/osops-utils.git', branch:'folsom'
cookbook 'dsh', git: 'https://github.com/rcbops-cookbooks/dsh.git', branch:'folsom'
cookbook 'exerstack', git: 'https://github.com/rcbops-cookbooks/exerstack.git', branch:'folsom'
cookbook 'kong', git: 'https://github.com/rcbops-cookbooks/kong.git', branch:'grizzly'
cookbook 'collectd', git: 'https://github.com/rcbops-cookbooks/collectd.git', branch:'folsom'
cookbook 'collectd-plugins', git: 'https://github.com/rcbops-cookbooks/collectd-plugins.git', branch:'folsom'
cookbook 'monit', git: 'https://github.com/rcbops-cookbooks/monit.git', branch:'folsom'
cookbook 'graphite', git: 'https://github.com/rcbops-cookbooks/graphite.git', branch:'folsom'
cookbook 'collectd-graphite', git: 'https://github.com/rcbops-cookbooks/collectd-graphite.git', branch:'folsom'
cookbook 'rsyslog', git: 'https://github.com/rcbops-cookbooks/rsyslog.git', branch:'folsom'
cookbook 'modules', git: 'https://github.com/rcbops-cookbooks/modules.git', branch:'folsom'
cookbook 'sysctl', git: 'https://github.com/rcbops-cookbooks/sysctl.git', branch:'folsom'
cookbook 'hardware', git: 'https://github.com/rcbops-cookbooks/hardware', branch:'folsom'
cookbook 'monitoring', git: 'https://github.com/rcbops-cookbooks/monitoring.git', branch:'folsom'
cookbook 'sosreport', git: 'https://github.com/rcbops-cookbooks/sosreport.git', branch:'folsom'
cookbook 'rabbitmq-openstack', git: 'https://github.com/rcbops-cookbooks/rabbitmq-openstack.git', branch:'folsom'
cookbook 'mysql-openstack', git: 'https://github.com/rcbops-cookbooks/mysql-openstack.git', branch:'folsom'
cookbook 'cinder', git: 'https://github.com/rcbops-cookbooks/cinder.git', branch:'folsom'
cookbook 'haproxy', git: 'https://github.com/rcbops-cookbooks/haproxy.git', branch:'folsom'
cookbook 'corosync', git: 'https://github.com/rcbops-cookbooks/corosync.git'
cookbook 'nova-network', git: 'https://github.com/rcbops-cookbooks/nova-network.git', branch:'folsom'
cookbook 'keepalived', git: 'https://github.com/rcbops-cookbooks/keepalived.git', branch:'folsom'
cookbook 'openstack-ha', git: 'https://github.com/rcbops-cookbooks/openstack-ha.git', branch:'folsom'

